### ISSUE TITLE
Getting this to work with Spring Roll

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/SoundJS#3]
I'm trying to port a game to Spring Roll, and I'm having difficulties with the Sound.

- Can I use sound Sprites? Example?
- Must everything be in a config upfront, can't my sounds be dynamic? For example...
- How do I get dynamic VO and Captions to work with this? (ie, "you scored",  "40", "2", "points")

**Comment by andrewstart** [comment]
Most of these questions would be more relevant to ask/answer on the [repo for SpringRoll itself](https://github.com/SpringRoll/SpringRoll). With SpringRoll, we moved away from using sound sprites, wanting to stick to the benefits of WebAudio (and Flash based fallbacks).
